import type { ChurchRow, EvidenceRow, ReviewRow, OutreachRow, ChurchContactRow, DashboardStats } from "@/lib/db";

/**
 * Seeded preview data — served when CIP_DEMO=1 so the whole UI can be explored
 * with no Supabase/keys. Realistic spread of statuses, scores, and sync states.
 */

export const demoStats: DashboardStats = {
  total: 1284,
  enriched: 912,
  reviewPending: 37,
  outreachReady: 268,
};

export const demoChurches: ChurchRow[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    original_row_id: "row-1001",
    name: "One City Church",
    city: "Nashville",
    state: "TN",
    website_verified: "https://theonecity.org",
    website_original: "https://theonecity.org",
    email_verified: "business@theonecity.org",
    phone_verified: "(615) 555-0142",
    lead_pastor: "Hollis Thomas",
    denomination: "Non-denominational",
    network_affiliation: "ARC",
    language: "English",
    active_status: "Verified Active",
    attendance_estimate: 850,
    attendance_min: 700,
    attendance_max: 1000,
    attendance_confidence: 82,
    attendance_confidence_tier: "High",
    mmc_fit_score: 88,
    influence_score: 74,
    multiplication_score: 69,
    digital_reach_score: 80,
    verification_score: 91,
    review_status: "approved",
    notes: "Squarespace + Planning Center + Pushpay. Single campus, strong digital footprint.",
    last_checked_at: "2026-06-28T14:20:00Z",
    updated_at: "2026-06-28T14:20:00Z",
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    original_row_id: "row-1002",
    name: "Cross Point Church",
    city: "Nashville",
    state: "TN",
    website_verified: "https://crosspoint.tv",
    website_original: "https://crosspoint.tv",
    email_verified: "hello@crosspoint.tv",
    phone_verified: "(615) 555-0199",
    lead_pastor: "Kevin Queen",
    denomination: "Non-denominational",
    network_affiliation: null,
    language: "English",
    active_status: "Verified Active",
    attendance_estimate: 5200,
    attendance_min: 4500,
    attendance_max: 6000,
    attendance_confidence: 78,
    attendance_confidence_tier: "High",
    mmc_fit_score: 84,
    influence_score: 91,
    multiplication_score: 82,
    digital_reach_score: 88,
    verification_score: 86,
    review_status: "approved",
    notes: "Multisite, 7 campuses across Middle Tennessee.",
    last_checked_at: "2026-06-27T09:05:00Z",
    updated_at: "2026-06-27T09:05:00Z",
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    original_row_id: "row-1003",
    name: "Grace Community Church",
    city: "Akron",
    state: "OH",
    website_verified: "https://gracecommunity.example",
    website_original: "https://gracecommunity.example",
    email_verified: null,
    phone_verified: "(330) 555-0177",
    lead_pastor: "Daniel Reyes",
    denomination: "Evangelical Free",
    network_affiliation: "EFCA",
    language: "English",
    active_status: "Likely Active",
    attendance_estimate: 420,
    attendance_min: 300,
    attendance_max: 550,
    attendance_confidence: 54,
    attendance_confidence_tier: "Medium",
    mmc_fit_score: 63,
    influence_score: 44,
    multiplication_score: 38,
    digital_reach_score: 41,
    verification_score: 58,
    review_status: "unreviewed",
    notes: null,
    last_checked_at: "2026-06-25T16:40:00Z",
    updated_at: "2026-06-25T16:40:00Z",
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    original_row_id: "row-1004",
    name: "Redemption Church",
    city: "Gilbert",
    state: "AZ",
    website_verified: "https://redemptionaz.com",
    website_original: "https://redemptionaz.com",
    email_verified: "info@redemptionaz.com",
    phone_verified: "(480) 555-0123",
    lead_pastor: "Luke Simmons",
    denomination: "Acts 29",
    network_affiliation: "Acts 29",
    language: "English",
    active_status: "Verified Active",
    attendance_estimate: 3100,
    attendance_min: 2600,
    attendance_max: 3600,
    attendance_confidence: 71,
    attendance_confidence_tier: "High",
    mmc_fit_score: 79,
    influence_score: 76,
    multiplication_score: 88,
    digital_reach_score: 72,
    verification_score: 83,
    review_status: "approved",
    notes: "Church-planting network hub; strong multiplication signals.",
    last_checked_at: "2026-06-26T11:15:00Z",
    updated_at: "2026-06-26T11:15:00Z",
  },
  {
    id: "55555555-5555-5555-5555-555555555555",
    original_row_id: "row-1005",
    name: "The Belonging Co",
    city: "Nashville",
    state: "TN",
    website_verified: "https://thebelonging.co",
    website_original: "https://thebelonging.co",
    email_verified: "connect@thebelonging.co",
    phone_verified: null,
    lead_pastor: "Henry Seeley",
    denomination: "Non-denominational",
    network_affiliation: null,
    language: "English",
    active_status: "Likely Active",
    attendance_estimate: 2800,
    attendance_min: 2200,
    attendance_max: 3400,
    attendance_confidence: 61,
    attendance_confidence_tier: "Medium",
    mmc_fit_score: 72,
    influence_score: 83,
    multiplication_score: 55,
    digital_reach_score: 90,
    verification_score: 64,
    review_status: "unreviewed",
    notes: null,
    last_checked_at: "2026-06-24T08:00:00Z",
    updated_at: "2026-06-24T08:00:00Z",
  },
  {
    id: "66666666-6666-6666-6666-666666666666",
    original_row_id: "row-1006",
    name: "Harvest Chapel",
    city: "Canton",
    state: "OH",
    website_verified: null,
    website_original: "https://harvestchapel.example",
    email_verified: null,
    phone_verified: "(330) 555-0210",
    lead_pastor: null,
    denomination: "Assemblies of God",
    network_affiliation: "AG",
    language: "English",
    active_status: "Uncertain",
    attendance_estimate: 180,
    attendance_min: 120,
    attendance_max: 260,
    attendance_confidence: 32,
    attendance_confidence_tier: "Low",
    mmc_fit_score: 41,
    influence_score: 28,
    multiplication_score: 22,
    digital_reach_score: 19,
    verification_score: 36,
    review_status: "needs_more_research",
    notes: null,
    last_checked_at: "2026-06-20T13:30:00Z",
    updated_at: "2026-06-20T13:30:00Z",
  },
];

const evidenceFor: EvidenceRow[] = [
  {
    field_name: "lead_pastor",
    proposed_value: "Hollis Thomas",
    evidence_text: "“Lead Pastor Hollis Thomas” — staff page.",
    source_url: "https://theonecity.org/staff",
    source_type: "official_site",
    confidence_score: 94,
    checked_at: "2026-06-28T14:20:00Z",
  },
  {
    field_name: "email_verified",
    proposed_value: "business@theonecity.org",
    evidence_text: "Footer contact block on the homepage.",
    source_url: "https://theonecity.org/",
    source_type: "official_site",
    confidence_score: 88,
    checked_at: "2026-06-28T14:20:00Z",
  },
  {
    field_name: "attendance_estimate",
    proposed_value: "850",
    evidence_text: "Service-times page lists two weekend gatherings; parking + room capacity cross-checked.",
    source_url: "https://theonecity.org/times",
    source_type: "official_site",
    confidence_score: 74,
    checked_at: "2026-06-28T14:20:00Z",
  },
  {
    field_name: "network_affiliation",
    proposed_value: "ARC",
    evidence_text: "Listed in the ARC church directory.",
    source_url: "https://arcchurches.com/directory",
    source_type: "directory",
    confidence_score: 69,
    checked_at: "2026-06-28T14:20:00Z",
  },
];

export function demoChurchContacts(churchId: string): ChurchContactRow[] {
  const base = [
    { email: "hollis@theonecity.org", name: "Hollis Thomas", role: "Lead Pastor", category: "person", confidence: 90, selected: true },
    { email: "business@theonecity.org", name: "Main office", role: null, category: "church", confidence: 82, selected: false },
    { email: "pastor@theonecity.org", name: null, role: "Lead Pastor", category: "role", confidence: 74, selected: false },
    { email: "worship@theonecity.org", name: "Worship Dept", role: "Worship", category: "role", confidence: 68, selected: false },
    { email: "kids@theonecity.org", name: "Kids Ministry", role: "Kids", category: "role", confidence: 61, selected: false },
    { email: "hello@theonecity.org", name: null, role: null, category: "unassigned", confidence: 40, selected: false },
  ];
  return base.map((c, i) => ({
    id: `demo-contact-${i}`,
    church_id: churchId,
    email: c.email,
    name: c.name,
    role: c.role,
    category: c.category,
    source_url: "https://theonecity.org/staff",
    confidence: c.confidence,
    selected_for_outreach: c.selected,
  }));
}

export function demoChurchDetail(id: string): {
  church: ChurchRow | null;
  evidence: EvidenceRow[];
  reviews: ReviewRow[];
} {
  const church = demoChurches.find((c) => c.id === id || c.original_row_id === id) ?? demoChurches[0];
  return {
    church,
    evidence: evidenceFor,
    reviews: demoReviews.filter((r) => r.church_id === church.id),
  };
}

export const demoReviews: ReviewRow[] = [
  {
    id: "rev-1",
    church_id: "33333333-3333-3333-3333-333333333333",
    field_name: "email_verified",
    current_value: null,
    proposed_value: "office@gracecommunity.example",
    confidence_score: 48,
    evidence_summary: "Found on a cached staff page; not confirmed on the live site.",
    source_urls: ["https://gracecommunity.example/staff"],
    review_status: "pending",
    created_at: "2026-06-25T16:41:00Z",
    reviewed_at: null,
    reviewer_notes: null,
    churches: { name: "Grace Community Church", city: "Akron", state: "OH" },
  },
  {
    id: "rev-2",
    church_id: "55555555-5555-5555-5555-555555555555",
    field_name: "lead_pastor",
    current_value: "Henry Seeley",
    proposed_value: "Henry & Alex Seeley",
    confidence_score: 52,
    evidence_summary: "Co-lead framing appears in recent messaging; single-name still on staff page.",
    source_urls: ["https://thebelonging.co/about"],
    review_status: "pending",
    created_at: "2026-06-24T08:02:00Z",
    reviewed_at: null,
    reviewer_notes: null,
    churches: { name: "The Belonging Co", city: "Nashville", state: "TN" },
  },
  {
    id: "rev-3",
    church_id: "66666666-6666-6666-6666-666666666666",
    field_name: "active_status",
    current_value: "Uncertain",
    proposed_value: "Closed",
    confidence_score: 39,
    evidence_summary: "No services listed after 2024; social accounts inactive 14+ months.",
    source_urls: ["https://facebook.com/harvestchapel"],
    review_status: "pending",
    created_at: "2026-06-20T13:35:00Z",
    reviewed_at: null,
    reviewer_notes: null,
    churches: { name: "Harvest Chapel", city: "Canton", state: "OH" },
  },
];

export const demoOutreachDate = "2026-07-04";
export const demoOutreach: OutreachRow[] = [
  {
    id: "out-1",
    church_id: "11111111-1111-1111-1111-111111111111",
    batch_date: demoOutreachDate,
    rank: 1,
    contact_name: "Hollis Thomas",
    contact_email: "business@theonecity.org",
    contact_role: "Lead Pastor",
    subject: "A quick idea for One City's next growth season",
    body: "Hi Hollis,\n\nI've been following One City's momentum in Nashville — the way you've built around Planning Center and Pushpay stands out. We help churches your size turn that digital foundation into measurable next-step engagement. Worth a 15-minute call next week?\n\n— MMC Team",
    approval_status: "approved",
    hubspot_sync_status: "synced",
    hubspot_contact_id: "hs-88421",
    fit_score: 88,
    churches: { name: "One City Church", city: "Nashville", state: "TN" },
  },
  {
    id: "out-2",
    church_id: "44444444-4444-4444-4444-444444444444",
    batch_date: demoOutreachDate,
    rank: 2,
    contact_name: "Luke Simmons",
    contact_email: "info@redemptionaz.com",
    contact_role: "Lead Pastor",
    subject: "Supporting Redemption's church-planting pipeline",
    body: "Hi Luke,\n\nRedemption's multiplication numbers are remarkable. As you plant, we can help each new site launch with the same engagement playbook from day one. Open to a short conversation?\n\n— MMC Team",
    approval_status: "pending",
    hubspot_sync_status: "not_synced",
    hubspot_contact_id: null,
    fit_score: 79,
    churches: { name: "Redemption Church", city: "Gilbert", state: "AZ" },
  },
  {
    id: "out-3",
    church_id: "22222222-2222-2222-2222-222222222222",
    batch_date: demoOutreachDate,
    rank: 3,
    contact_name: "Kevin Queen",
    contact_email: "hello@crosspoint.tv",
    contact_role: "Lead Pastor",
    subject: "Cross Point across 7 campuses — one engagement view",
    body: "Hi Kevin,\n\nRunning engagement consistently across 7 campuses is hard. We give multisite teams a single view of next-steps by location. Could I show you what that looks like?\n\n— MMC Team",
    approval_status: "pending",
    hubspot_sync_status: "queued",
    hubspot_contact_id: null,
    fit_score: 84,
    churches: { name: "Cross Point Church", city: "Nashville", state: "TN" },
  },
  {
    id: "out-4",
    church_id: "55555555-5555-5555-5555-555555555555",
    batch_date: demoOutreachDate,
    rank: 4,
    contact_name: null,
    contact_email: "connect@thebelonging.co",
    contact_role: "General",
    subject: "The Belonging Co — turning reach into next steps",
    body: "Hello,\n\nThe Belonging Co's digital reach is exceptional. We help translate that audience into in-person next steps. Who's the best person to talk with about engagement?\n\n— MMC Team",
    approval_status: "rejected",
    hubspot_sync_status: "not_synced",
    hubspot_contact_id: null,
    fit_score: 72,
    churches: { name: "The Belonging Co", city: "Nashville", state: "TN" },
  },
];
